### ISSUE TITLE
i can't get variable message to print anything

### ISSUE THREAD

**Issue by raditharch** [njdreikosen/email_listener#3]
# Get the emails currently unread in the inbox
messages = el.scrape()
print(messages)

based on code's above, the terminal should print out variable massage which is :

{'227_somebody@gmail.com': {'Subject': 'EmailListener Test', 'Plain_Text': 'This is the plain text message.\r\nThis is another line.\r\n', 'Plain_HTML': 'This is the HTML message.  \nThis is another line.  \n\n', 'HTML': '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">\r\n<html xmlns="http://www.w3.org/1999/xhtml">\r\n  <head>\r\n    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />\r\n    <title>EmailListener Test</title>\r\n    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>\r\n  </head>\r\n  <body>\r\n    <p>This is the HTML message.<br/>This is another line.<br/></p>\r\n  </body>\r\n</html>', 'attachments': ['/home/pi/email_listener/tests/attachments/EmailListener_test.txt']}} 

the terminal output.

Connection is now in IDLE mode.
Server sent: [(40, b'EXISTS')]
PROCESSING: Email UID = 73 from xxxx.xxxxx.xxxx@gmail.com
Server sent: nothing
Server sent: nothing
Server sent: nothing

but the thing that i got only the result it is already downloaded in notepad. any ideas why is it happening ?

**Comment by njdreikosen** [comment]
I'm not sure why that wouldn't be working, can you post a larger chunk of your code?

**Comment by raditharch** [comment]
@njdreikosen hi, I already solve the problem with directly editing from original repository. It's seems maybe because it was using class so needed declaration as global variable.

here my code
![image](https://user-images.githubusercontent.com/72731175/119092670-e94cee00-ba38-11eb-8ba3-a32e61a341fa.png)

using print inside the function scrape itself was no problem. 
![image](https://user-images.githubusercontent.com/72731175/119093151-860f8b80-ba39-11eb-84c0-a093a23e57dd.png)

**Comment by raditharch** [comment]
I will close the issue, because the problem only need using print inside master repository.
